const employeeData = [
  { 
    sr: 1,
    div: "ENG",
    staff_id: "EMP002", 
    name: "Jane Smith", 
    doorlog: "JS002",
    dept: "Engineering",
    team: "Development Team A",
    status: "inactive",
    role: "Software Engineer",
    id: 1002,
    email: "jane.smith@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP002",
    department_dir_id: 1,
    team_id: 1,
    title_id: 1,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-15T00:00:00Z"
  },
  { 
    sr: 2,
    div: "PROD",
    staff_id: "EMP003", 
    name: "Mike Johnson", 
    doorlog: "MJ003",
    dept: "Product",
    team: "Product Team A",
    status: "active",
    role: "Product Manager",
    id: 1003,
    email: "mike.johnson@company.com",
    is_core_personnel: false,
    has_japan_business_trip: true,
    employee_code: "EMP003",
    department_dir_id: 2,
    team_id: 2,
    title_id: 2,
    role_id: 2,
    is_admin: false,
    created_at: "2024-02-20T00:00:00Z"
  },
  { 
    sr: 3,
    div: "ENG",
    staff_id: "EMP004", 
    name: "Sarah Wilson", 
    doorlog: "SW004",
    dept: "Engineering",
    team: "Development Team B",
    status: "active",
    role: "Senior Developer",
    id: 1004,
    email: "sarah.wilson@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP004",
    department_dir_id: 1,
    team_id: 3,
    title_id: 3,
    role_id: 1,
    is_admin: false,
    created_at: "2024-03-10T00:00:00Z"
  },
  { 
    sr: 4,
    div: "SALES",
    staff_id: "EMP005", 
    name: "David Brown", 
    doorlog: "DB005",
    dept: "Sales",
    team: "Sales Team A",
    status: "active",
    role: "Sales Representative",
    id: 1005,
    email: "david.brown@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP005",
    department_dir_id: 3,
    team_id: 4,
    title_id: 4,
    role_id: 3,
    is_admin: false,
    created_at: "2024-01-25T00:00:00Z"
  },
  { 
    sr: 5,
    div: "ENG",
    staff_id: "EMP006", 
    name: "Emily Chen", 
    doorlog: "EC006",
    dept: "Engineering",
    team: "Development Team A",
    status: "active",
    role: "Tech Lead",
    id: 1006,
    email: "emily.chen@company.com",
    is_core_personnel: true,
    has_japan_business_trip: true,
    employee_code: "EMP006",
    department_dir_id: 1,
    team_id: 1,
    title_id: 5,
    role_id: 1,
    is_admin: false,
    created_at: "2024-02-05T00:00:00Z"
  },
  { 
    sr: 6,
    div: "MKT",
    staff_id: "EMP007", 
    name: "Robert Taylor", 
    doorlog: "RT007",
    dept: "Marketing",
    team: "Marketing Team A",
    status: "active",
    role: "Marketing Specialist",
    id: 1007,
    email: "robert.taylor@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP007",
    department_dir_id: 4,
    team_id: 5,
    title_id: 2,
    role_id: 2,
    is_admin: false,
    created_at: "2024-03-15T00:00:00Z"
  },
  { 
    sr: 7,
    div: "ENG",
    staff_id: "EMP008", 
    name: "Lisa Anderson", 
    doorlog: "LA008",
    dept: "Engineering",
    team: "Development Team C",
    status: "active",
    role: "Junior Developer",
    id: 1008,
    email: "lisa.anderson@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP008",
    department_dir_id: 1,
    team_id: 2,
    title_id: 1,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-18T00:00:00Z"
  },
  { 
    sr: 8,
    div: "PROD",
    staff_id: "EMP009", 
    name: "James Martinez", 
    doorlog: "JM009",
    dept: "Product",
    team: "Product Team B",
    status: "active",
    role: "Product Owner",
    id: 1009,
    email: "james.martinez@company.com",
    is_core_personnel: true,
    has_japan_business_trip: true,
    employee_code: "EMP009",
    department_dir_id: 2,
    team_id: 3,
    title_id: 3,
    role_id: 2,
    is_admin: false,
    created_at: "2024-02-12T00:00:00Z"
  },
  { 
    sr: 9,
    div: "SALES",
    staff_id: "EMP010", 
    name: "Maria Garcia", 
    doorlog: "MG010",
    dept: "Sales",
    team: "Sales Team B",
    status: "active",
    role: "Account Manager",
    id: 1010,
    email: "maria.garcia@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP010",
    department_dir_id: 3,
    team_id: 4,
    title_id: 2,
    role_id: 3,
    is_admin: false,
    created_at: "2024-03-20T00:00:00Z"
  },
  { 
    sr: 10,
    div: "ENG",
    staff_id: "EMP011", 
    name: "Thomas Anderson", 
    doorlog: "TA011",
    dept: "Engineering",
    team: "Development Team A",
    status: "active",
    role: "Architect",
    id: 1011,
    email: "thomas.anderson@company.com",
    is_core_personnel: true,
    has_japan_business_trip: true,
    employee_code: "EMP011",
    department_dir_id: 1,
    team_id: 1,
    title_id: 5,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-30T00:00:00Z"
  },
  { 
    sr: 11,
    div: "PROD",
    staff_id: "EMP012", 
    name: "Jennifer Lee", 
    doorlog: "JL012",
    dept: "Product",
    team: "Product Team A",
    status: "active",
    role: "Business Analyst",
    id: 1012,
    email: "jennifer.lee@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP012",
    department_dir_id: 2,
    team_id: 2,
    title_id: 1,
    role_id: 2,
    is_admin: false,
    created_at: "2024-02-28T00:00:00Z"
  },
  { 
    sr: 12,
    div: "ENG",
    staff_id: "EMP013", 
    name: "Michael Chang", 
    doorlog: "MC013",
    dept: "Engineering",
    team: "Development Team B",
    status: "active",
    role: "Software Engineer",
    id: 1013,
    email: "michael.chang@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP013",
    department_dir_id: 1,
    team_id: 3,
    title_id: 3,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-22T00:00:00Z"
  },
  { 
    sr: 13,
    div: "MKT",
    staff_id: "EMP014", 
    name: "Rachel Green", 
    doorlog: "RG014",
    dept: "Marketing",
    team: "Marketing Team B",
    status: "active",
    role: "Marketing Manager",
    id: 1014,
    email: "rachel.green@company.com",
    is_core_personnel: false,
    has_japan_business_trip: true,
    employee_code: "EMP014",
    department_dir_id: 4,
    team_id: 5,
    title_id: 2,
    role_id: 3,
    is_admin: false,
    created_at: "2024-03-05T00:00:00Z"
  },
  { 
    sr: 14,
    div: "ENG",
    staff_id: "EMP015", 
    name: "Daniel Kim", 
    doorlog: "DK015",
    dept: "Engineering",
    team: "Development Team A",
    status: "active",
    role: "Senior Developer",
    id: 1015,
    email: "daniel.kim@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP015",
    department_dir_id: 1,
    team_id: 1,
    title_id: 4,
    role_id: 1,
    is_admin: false,
    created_at: "2024-02-14T00:00:00Z"
  },
  { 
    sr: 15,
    div: "PROD",
    staff_id: "EMP016", 
    name: "Sophia Martinez", 
    doorlog: "SM016",
    dept: "Product",
    team: "Product Team B",
    status: "active",
    role: "Product Analyst",
    id: 1016,
    email: "sophia.martinez@company.com",
    is_core_personnel: false,
    has_japan_business_trip: true,
    employee_code: "EMP016",
    department_dir_id: 2,
    team_id: 2,
    title_id: 1,
    role_id: 2,
    is_admin: false,
    created_at: "2024-03-12T00:00:00Z"
  },
  { 
    sr: 16,
    div: "SALES",
    staff_id: "EMP017", 
    name: "Oliver Wilson", 
    doorlog: "OW017",
    dept: "Sales",
    team: "Sales Team A",
    status: "active",
    role: "Sales Manager",
    id: 1017,
    email: "oliver.wilson@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP017",
    department_dir_id: 3,
    team_id: 4,
    title_id: 2,
    role_id: 3,
    is_admin: false,
    created_at: "2024-01-28T00:00:00Z"
  },
  { 
    sr: 17,
    div: "ENG",
    staff_id: "EMP018", 
    name: "Emma Thompson", 
    doorlog: "ET018",
    dept: "Engineering",
    team: "Development Team B",
    status: "active",
    role: "Tech Lead",
    id: 1018,
    email: "emma.thompson@company.com",
    is_core_personnel: true,
    has_japan_business_trip: true,
    employee_code: "EMP018",
    department_dir_id: 1,
    team_id: 3,
    title_id: 5,
    role_id: 1,
    is_admin: false,
    created_at: "2024-02-18T00:00:00Z"
  },
  { 
    sr: 18,
    div: "PROD",
    staff_id: "EMP019", 
    name: "William Parker", 
    doorlog: "WP019",
    dept: "Product",
    team: "Product Team A",
    status: "active",
    role: "Product Manager",
    id: 1019,
    email: "william.parker@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP019",
    department_dir_id: 2,
    team_id: 1,
    title_id: 3,
    role_id: 2,
    is_admin: false,
    created_at: "2024-03-25T00:00:00Z"
  },
  { 
    sr: 19,
    div: "MKT",
    staff_id: "EMP020", 
    name: "Olivia Brown", 
    doorlog: "OB020",
    dept: "Marketing",
    team: "Marketing Team A",
    status: "active",
    role: "Social Media Manager",
    id: 1020,
    email: "olivia.brown@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP020",
    department_dir_id: 4,
    team_id: 5,
    title_id: 1,
    role_id: 3,
    is_admin: false,
    created_at: "2024-01-12T00:00:00Z"
  },
  { 
    sr: 20,
    div: "ENG",
    staff_id: "EMP021", 
    name: "James Wilson", 
    doorlog: "JW021",
    dept: "Engineering",
    team: "Development Team C",
    status: "active",
    role: "Software Architect",
    id: 1021,
    email: "james.wilson@company.com",
    is_core_personnel: true,
    has_japan_business_trip: true,
    employee_code: "EMP021",
    department_dir_id: 1,
    team_id: 2,
    title_id: 4,
    role_id: 1,
    is_admin: false,
    created_at: "2024-02-22T00:00:00Z"
  },
  { 
    sr: 21,
    div: "SALES",
    staff_id: "EMP022", 
    name: "Natalie Davis", 
    doorlog: "ND022",
    dept: "Sales",
    team: "Sales Team B",
    status: "active",
    role: "Sales Representative",
    id: 1022,
    email: "natalie.davis@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP022",
    department_dir_id: 3,
    team_id: 4,
    title_id: 2,
    role_id: 2,
    is_admin: false,
    created_at: "2024-03-08T00:00:00Z"
  },
  { 
    sr: 22,
    div: "PROD",
    staff_id: "EMP023", 
    name: "Ryan Garcia", 
    doorlog: "RG023",
    dept: "Product",
    team: "Product Team B",
    status: "active",
    role: "Product Owner",
    id: 1023,
    email: "ryan.garcia@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP023",
    department_dir_id: 2,
    team_id: 3,
    title_id: 3,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-20T00:00:00Z"
  },
  { 
    sr: 23,
    div: "ENG",
    staff_id: "EMP024", 
    name: "Isabella White", 
    doorlog: "IW024",
    dept: "Engineering",
    team: "Development Team A",
    status: "active",
    role: "Junior Developer",
    id: 1024,
    email: "isabella.white@company.com",
    is_core_personnel: false,
    has_japan_business_trip: true,
    employee_code: "EMP024",
    department_dir_id: 1,
    team_id: 1,
    title_id: 1,
    role_id: 1,
    is_admin: false,
    created_at: "2024-02-08T00:00:00Z"
  },
  { 
    sr: 24,
    div: "MKT",
    staff_id: "EMP025", 
    name: "Ethan Taylor", 
    doorlog: "ET025",
    dept: "Marketing",
    team: "Marketing Team B",
    status: "active",
    role: "Content Creator",
    id: 1025,
    email: "ethan.taylor@company.com",
    is_core_personnel: false,
    has_japan_business_trip: false,
    employee_code: "EMP025",
    department_dir_id: 4,
    team_id: 5,
    title_id: 2,
    role_id: 3,
    is_admin: false,
    created_at: "2024-03-18T00:00:00Z"
  },
  { 
    sr: 25,
    div: "ENG",
    staff_id: "EMP026", 
    name: "Mia Rodriguez", 
    doorlog: "MR026",
    dept: "Engineering",
    team: "Development Team C",
    status: "active",
    role: "Software Engineer",
    id: 1026,
    email: "mia.rodriguez@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP026",
    department_dir_id: 1,
    team_id: 2,
    title_id: 5,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-08T00:00:00Z"
  },
  { 
    sr: 26,
    div: "PROD",
    staff_id: "EMP027", 
    name: "Alexander Martinez", 
    doorlog: "AM027",
    dept: "Product",
    team: "Product Team A",
    status: "active",
    role: "Business Analyst",
    id: 1027,
    email: "alexander.martinez@company.com",
    is_core_personnel: false,
    has_japan_business_trip: true,
    employee_code: "EMP027",
    department_dir_id: 2,
    team_id: 3,
    title_id: 3,
    role_id: 2,
    is_admin: false,
    created_at: "2024-02-25T00:00:00Z"
  },
  { 
    sr: 27,
    div: "SALES",
    staff_id: "EMP028", 
    name: "Charlotte Moore", 
    doorlog: "CM028",
    dept: "Sales",
    team: "Sales Team A",
    status: "active",
    role: "Account Executive",
    id: 1028,
    email: "charlotte.moore@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP028",
    department_dir_id: 3,
    team_id: 4,
    title_id: 1,
    role_id: 3,
    is_admin: false,
    created_at: "2024-03-22T00:00:00Z"
  },
  { 
    sr: 28,
    div: "ENG",
    staff_id: "EMP029", 
    name: "Liam Anderson", 
    doorlog: "LA029",
    dept: "Engineering",
    team: "Development Team A",
    status: "active",
    role: "DevOps Engineer",
    id: 1029,
    email: "liam.anderson@company.com",
    is_core_personnel: false,
    has_japan_business_trip: true,
    employee_code: "EMP029",
    department_dir_id: 1,
    team_id: 1,
    title_id: 2,
    role_id: 1,
    is_admin: false,
    created_at: "2024-01-05T00:00:00Z"
  },
  { 
    sr: 29,
    div: "PROD",
    staff_id: "EMP030", 
    name: "Amelia Thomas", 
    doorlog: "AT030",
    dept: "Product",
    team: "Product Team B",
    status: "active",
    role: "Product Manager",
    id: 1030,
    email: "amelia.thomas@company.com",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP030",
    department_dir_id: 2,
    team_id: 2,
    title_id: 4,
    role_id: 2,
    is_admin: false,
    created_at: "2024-02-28T00:00:00Z"
  }
];

export const employeeDataStore = (set, get) => ({
  employee_data: [],
  
  fetch_EmployeeData: async () => {
    set({ employee_data: employeeData });
  },
});