// store/employee_data_store.ts
import { Employee_StoreType } from "../types"

const employeeData = [
  {
    sr: 1,
    div: "002",
    staff_id: "EMP001",
    name: "John Doe",
    doorlog: "JD001",
    dept: "Information Technology",
    team: "Frontend Team",
    status: "active",
    role: "admin",
    id: 1001,
    email: "john.doe@company.com",
    phone: "+1234567890",
    join_date: "2024-01-15",
    address: "123 Main St, City",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP001",
    department_dir_id: 1,
    team_id: 1,
    title_id: 1,
    role_id: 1,
    is_admin: true,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    sr: 2,
    div: "002",
    staff_id: "EMP002",
    name: "Jane Smith",
    doorlog: "JS002",
    dept: "Engineering",
    team: "Development Team A",
    status: "active",
    role: "approver",
    id: 1002,
    email: "jane.smith@company.com",
    phone: "+1234567891",
    join_date: "2024-02-01",
    address: "456 Oak Ave, City",
    is_core_personnel: true,
    has_japan_business_trip: false,
    employee_code: "EMP002",
    department_dir_id: 1,
    team_id: 1,
    title_id: 1,
    role_id: 1,
    is_admin: false,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    sr: 3,
    div: "003",
    staff_id: "EMP003",
    name: "Mike Johnson",
    email: "mike.johnson@company.com",
    doorlog: "MJ003",
    dept: "Product Division",
    team: "Product Team A",
    status: "active",
    role: "learner",
    id: 1003,
    phone: "+1234567892",
    join_date: "2024-02-15",
    address: "789 Pine Rd, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 4,
    div: "002",
    staff_id: "EMP004",
    name: "Sarah Wilson",
    email: "sarah.wilson@company.com",
    doorlog: "SW004",
    dept: "Quality Assurance",
    team: "Development Team B",
    status: "active",
    role: "learner",
    id: 1004,
    phone: "+1234567893",
    join_date: "2024-03-01",
    address: "321 Elm St, City",
    is_admin: false,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 5,
    div: "003",
    staff_id: "EMP005",
    name: "David Brown",
    email: "david.brown@company.com",
    doorlog: "DB005",
    dept: "Sales Division",
    team: "Sales Team A",
    status: "inactive",
    role: "learner",
    id: 1005,
    phone: "+1234567894",
    join_date: "2024-03-15",
    address: "654 Maple Dr, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 6,
    div: "002",
    staff_id: "EMP006",
    name: "Emily Chen",
    email: "emily.chen@company.com",
    doorlog: "EC006",
    dept: "Software Development",
    team: "Development Team A",
    status: "active",
    role: "admin",
    id: 1006,
    phone: "+1234567895",
    join_date: "2024-04-01",
    address: "987 Cedar Ln, City",
    is_admin: true,
    is_core_personnel: true,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 7,
    div: "003",
    staff_id: "EMP007",
    name: "Robert Taylor",
    email: "robert.taylor@company.com",
    doorlog: "RT007",
    dept: "Marketing Division",
    team: "Marketing Team A",
    status: "active",
    role: "approver",
    id: 1007,
    phone: "+1234567896",
    join_date: "2024-04-15",
    address: "147 Birch Blvd, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 8,
    div: "002",
    staff_id: "EMP008",
    name: "Lisa Anderson",
    email: "lisa.anderson@company.com",
    doorlog: "LA008",
    dept: "Infrastructure",
    team: "Development Team C",
    status: "active",
    role: "learner",
    id: 1008,
    phone: "+1234567897",
    join_date: "2024-05-01",
    address: "258 Spruce Way, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 9,
    div: "003",
    staff_id: "EMP009",
    name: "James Martinez",
    email: "james.martinez@company.com",
    doorlog: "JM009",
    dept: "Product Strategy",
    team: "Product Team B",
    status: "active",
    role: "approver",
    id: 1009,
    phone: "+1234567898",
    join_date: "2024-05-15",
    address: "369 Willow Ct, City",
    is_admin: false,
    is_core_personnel: true,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 10,
    div: "002",
    staff_id: "EMP010",
    name: "Maria Garcia",
    email: "maria.garcia@company.com",
    doorlog: "MG010",
    dept: "Account Management",
    team: "Sales Team B",
    status: "active",
    role: "learner",
    id: 1010,
    phone: "+1234567899",
    join_date: "2024-06-01",
    address: "741 Aspen St, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 11,
    div: "003",
    staff_id: "EMP011",
    name: "Daniel Kim",
    email: "daniel.kim@company.com",
    doorlog: "DK011",
    dept: "Research & Development",
    team: "R&D Team A",
    status: "active",
    role: "admin",
    id: 1011,
    phone: "+1234567800",
    join_date: "2024-06-15",
    address: "852 Maple Ave, City",
    is_admin: true,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 12,
    div: "002",
    staff_id: "EMP012",
    name: "Jennifer Lee",
    email: "jennifer.lee@company.com",
    doorlog: "JL012",
    dept: "Human Resources",
    team: "HR Team",
    status: "active",
    role: "approver",
    id: 1012,
    phone: "+1234567801",
    join_date: "2024-07-01",
    address: "963 Oak Rd, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 13,
    div: "003",
    staff_id: "EMP013",
    name: "Michael Chang",
    email: "michael.chang@company.com",
    doorlog: "MC013",
    dept: "Finance",
    team: "Finance Team",
    status: "inactive",
    role: "learner",
    id: 1013,
    phone: "+1234567802",
    join_date: "2024-07-15",
    address: "159 Pine St, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 14,
    div: "002",
    staff_id: "EMP014",
    name: "Rachel Green",
    email: "rachel.green@company.com",
    doorlog: "RG014",
    dept: "Digital Marketing",
    team: "Marketing Team B",
    status: "active",
    role: "approver",
    id: 1014,
    phone: "+1234567803",
    join_date: "2024-08-01",
    address: "753 Elm Blvd, City",
    is_admin: false,
    is_core_personnel: true,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 15,
    div: "003",
    staff_id: "EMP015",
    name: "Thomas Brown",
    email: "thomas.brown@company.com",
    doorlog: "TB015",
    dept: "Legal",
    team: "Legal Team",
    status: "active",
    role: "learner",
    id: 1015,
    phone: "+1234567804",
    join_date: "2024-08-15",
    address: "246 Cedar Ln, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 16,
    div: "002",
    staff_id: "EMP016",
    name: "Sophia Martinez",
    email: "sophia.martinez@company.com",
    doorlog: "SM016",
    dept: "Product Management",
    team: "Product Team C",
    status: "active",
    role: "admin",
    id: 1016,
    phone: "+1234567805",
    join_date: "2024-09-01",
    address: "357 Spruce Dr, City",
    is_admin: true,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 17,
    div: "003",
    staff_id: "EMP017",
    name: "Oliver Wilson",
    email: "oliver.wilson@company.com",
    doorlog: "OW017",
    dept: "Operations",
    team: "Operations Team A",
    status: "active",
    role: "approver",
    id: 1017,
    phone: "+1234567806",
    join_date: "2024-09-15",
    address: "468 Birch Way, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 18,
    div: "002",
    staff_id: "EMP018",
    name: "Emma Thompson",
    email: "emma.thompson@company.com",
    doorlog: "ET018",
    dept: "Customer Support",
    team: "Support Team A",
    status: "active",
    role: "learner",
    id: 1018,
    phone: "+1234567807",
    join_date: "2024-10-01",
    address: "579 Willow Ct, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 19,
    div: "003",
    staff_id: "EMP019",
    name: "William Parker",
    email: "william.parker@company.com",
    doorlog: "WP019",
    dept: "Security",
    team: "Security Team",
    status: "inactive",
    role: "learner",
    id: 1019,
    phone: "+1234567808",
    join_date: "2024-10-15",
    address: "681 Aspen Ave, City",
    is_admin: false,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 20,
    div: "002",
    staff_id: "EMP020",
    name: "Olivia Brown",
    email: "olivia.brown@company.com",
    doorlog: "OB020",
    dept: "Data Science",
    team: "Data Team A",
    status: "active",
    role: "admin",
    id: 1020,
    phone: "+1234567809",
    join_date: "2024-11-01",
    address: "792 Oak Dr, City",
    is_admin: true,
    is_core_personnel: true,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 21,
    div: "003",
    staff_id: "EMP021",
    name: "James Wilson",
    email: "james.wilson@company.com",
    doorlog: "JW021",
    dept: "Infrastructure",
    team: "DevOps Team",
    status: "active",
    role: "approver",
    id: 1021,
    phone: "+1234567810",
    join_date: "2024-11-15",
    address: "903 Maple St, City",
    is_admin: false,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 22,
    div: "002",
    staff_id: "EMP022",
    name: "Ava Johnson",
    email: "ava.johnson@company.com",
    doorlog: "AJ022",
    dept: "UX Design",
    team: "Design Team A",
    status: "active",
    role: "learner",
    id: 1022,
    phone: "+1234567811",
    join_date: "2024-12-01",
    address: "147 Cedar Rd, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 23,
    div: "003",
    staff_id: "EMP023",
    name: "Ethan Davis",
    email: "ethan.davis@company.com",
    doorlog: "ED023",
    dept: "Mobile Development",
    team: "Mobile Team",
    status: "active",
    role: "learner",
    id: 1023,
    phone: "+1234567812",
    join_date: "2024-12-15",
    address: "258 Pine Blvd, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 24,
    div: "002",
    staff_id: "EMP024",
    name: "Mia Rodriguez",
    email: "mia.rodriguez@company.com",
    doorlog: "MR024",
    dept: "Cloud Computing",
    team: "Cloud Team A",
    status: "active",
    role: "admin",
    id: 1024,
    phone: "+1234567813",
    join_date: "2025-01-01",
    address: "369 Elm Way, City",
    is_admin: true,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 25,
    div: "003",
    staff_id: "EMP025",
    name: "Noah Martinez",
    email: "noah.martinez@company.com",
    doorlog: "NM025",
    dept: "AI Research",
    team: "AI Team",
    status: "active",
    role: "approver",
    id: 1025,
    phone: "+1234567814",
    join_date: "2025-01-15",
    address: "471 Spruce Ln, City",
    is_admin: false,
    is_core_personnel: true,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 26,
    div: "002",
    staff_id: "EMP026",
    name: "Isabella Garcia",
    email: "isabella.garcia@company.com",
    doorlog: "IG026",
    dept: "Business Intelligence",
    team: "BI Team",
    status: "active",
    role: "learner",
    id: 1026,
    phone: "+1234567815",
    join_date: "2025-02-01",
    address: "582 Birch Ct, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 27,
    div: "003",
    staff_id: "EMP027",
    name: "Liam Taylor",
    email: "liam.taylor@company.com",
    doorlog: "LT027",
    dept: "Technical Writing",
    team: "Documentation Team",
    status: "inactive",
    role: "learner",
    id: 1027,
    phone: "+1234567816",
    join_date: "2025-02-15",
    address: "693 Willow Dr, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 28,
    div: "002",
    staff_id: "EMP028",
    name: "Charlotte White",
    email: "charlotte.white@company.com",
    doorlog: "CW028",
    dept: "Procurement",
    team: "Procurement Team",
    status: "active",
    role: "approver",
    id: 1028,
    phone: "+1234567817",
    join_date: "2025-03-01",
    address: "804 Oak Ave, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: false,
    position: null,
  },
  {
    sr: 29,
    div: "003",
    staff_id: "EMP029",
    name: "Amelia Moore",
    email: "amelia.moore@company.com",
    doorlog: "AM029",
    dept: "Logistics",
    team: "Logistics Team A",
    status: "active",
    role: "learner",
    id: 1029,
    phone: "+1234567818",
    join_date: "2025-03-15",
    address: "915 Maple Rd, City",
    is_admin: false,
    is_core_personnel: false,
    has_japan_business_trip: true,
    position: null,
  },
  {
    sr: 30,
    div: "002",
    staff_id: "EMP030",
    name: "Benjamin Harris",
    email: "benjamin.harris@company.com",
    doorlog: "BH030",
    dept: "Internal Audit",
    team: "Audit Team",
    status: "active",
    role: "admin",
    id: 1030,
    phone: "+1234567819",
    join_date: "2025-04-01",
    address: "126 Pine St, City",
    is_admin: true,
    is_core_personnel: true,
    has_japan_business_trip: false,
    position: null,
  },
]

type StoreSet = (
  fn: (state: Employee_StoreType) => Partial<Employee_StoreType>
) => void
type StoreGet = () => Employee_StoreType

// Helper functions to extract unique values
export const getUniqueDivisions = (employees: any[]) => {
  const divisions = employees.map((emp) => emp.div).filter(Boolean)
  return [...new Set(divisions)].map((div) => ({ value: div, label: div }))
}

export const getUniqueDepartments = (employees: any[]) => {
  const departments = employees.map((emp) => emp.dept).filter(Boolean)
  return [...new Set(departments)].map((dept) => ({ value: dept, label: dept }))
}

export const getUniqueTeams = (employees: any[]) => {
  const teams = employees.map((emp) => emp.team).filter(Boolean)
  return [...new Set(teams)].map((team) => ({ value: team, label: team }))
}

export const getUniqueRoles = (employees: any[]) => {
  const roles = employees.map((emp) => emp.role).filter(Boolean)
  return [...new Set(roles)].map((role) => ({ value: role, label: role }))
}

export const employeeDataStore = (set: StoreSet, get: StoreGet) => ({
  employee_data: [],

  // Dynamic options that will be populated from employee data
  division_options: [],
  department_options: [],
  team_options: [],
  role_options: [],

  fetch_EmployeeData: async () => {
    set(() => ({ employee_data: employeeData }))

    // Extract unique values for dropdowns
    const divisions = getUniqueDivisions(employeeData)
    const departments = getUniqueDepartments(employeeData)
    const teams = getUniqueTeams(employeeData)
    const roles = getUniqueRoles(employeeData)

    set((state) => ({
      ...state,
      division_options: divisions,
      department_options: departments,
      team_options: teams,
      role_options: roles,
    }))
  },
})
