import { Employee_StoreType } from "../types"

const employeeData = [
  {
    "sr": 1,
    "id": "1002",
    "staff_id": "EMP002",
    "name": "Jane Smith",
    "email": "jane.smith@company.com",
    "doorlog": "JS002",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": false,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Software Development Dept",
    "team": "Development Team A",
    "role": "Software Engineer",
    "position": null
  },
  {
    "sr": 2,
    "id": "1003",
    "staff_id": "EMP003",
    "name": "Mike Johnson",
    "email": "mike.johnson@company.com",
    "doorlog": "MJ003",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": true,
    "div": "PROD",
    "dept_dir": "Product Division",
    "dept_dat": "Product Management Dept",
    "team": "Product Team A",
    "role": "Product Manager",
    "position": null
  },
  {
    "sr": 3,
    "id": "1004",
    "staff_id": "EMP004",
    "name": "Sarah Wilson",
    "email": "sarah.wilson@company.com",
    "doorlog": "SW004",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": false,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Quality Assurance Dept",
    "team": "Development Team B",
    "role": "Senior Developer",
    "position": null
  },
  {
    "sr": 4,
    "id": "1005",
    "staff_id": "EMP005",
    "name": "David Brown",
    "email": "david.brown@company.com",
    "doorlog": "DB005",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "SALES",
    "dept_dir": "Sales Division",
    "dept_dat": "Regional Sales Dept",
    "team": "Sales Team A",
    "role": "Sales Representative",
    "position": null
  },
  {
    "sr": 5,
    "id": "1006",
    "staff_id": "EMP006",
    "name": "Emily Chen",
    "email": "emily.chen@company.com",
    "doorlog": "EC006",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": true,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Software Development Dept",
    "team": "Development Team A",
    "role": "Tech Lead",
    "position": null
  },
  {
    "sr": 6,
    "id": "1007",
    "staff_id": "EMP007",
    "name": "Robert Taylor",
    "email": "robert.taylor@company.com",
    "doorlog": "RT007",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "MKT",
    "dept_dir": "Marketing Division",
    "dept_dat": "Digital Marketing Dept",
    "team": "Marketing Team A",
    "role": "Marketing Specialist",
    "position": null
  },
  {
    "sr": 7,
    "id": "1008",
    "staff_id": "EMP008",
    "name": "Lisa Anderson",
    "email": "lisa.anderson@company.com",
    "doorlog": "LA008",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Infrastructure Dept",
    "team": "Development Team C",
    "role": "Junior Developer",
    "position": null
  },
  {
    "sr": 8,
    "id": "1009",
    "staff_id": "EMP009",
    "name": "James Martinez",
    "email": "james.martinez@company.com",
    "doorlog": "JM009",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": true,
    "div": "PROD",
    "dept_dir": "Product Division",
    "dept_dat": "Product Strategy Dept",
    "team": "Product Team B",
    "role": "Product Owner",
    "position": null
  },
  {
    "sr": 9,
    "id": "1010",
    "staff_id": "EMP010",
    "name": "Maria Garcia",
    "email": "maria.garcia@company.com",
    "doorlog": "MG010",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "SALES",
    "dept_dir": "Sales Division",
    "dept_dat": "Account Management Dept",
    "team": "Sales Team B",
    "role": "Account Manager",
    "position": null
  },
  {
    "sr": 10,
    "id": "1011",
    "staff_id": "EMP011",
    "name": "Thomas Anderson",
    "email": "thomas.anderson@company.com",
    "doorlog": "TA011",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": true,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Software Development Dept",
    "team": "Development Team A",
    "role": "Architect",
    "position": null
  },
  {
    "sr": 11,
    "id": "1012",
    "staff_id": "EMP012",
    "name": "Jennifer Lee",
    "email": "jennifer.lee@company.com",
    "doorlog": "JL012",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "PROD",
    "dept_dir": "Product Division",
    "dept_dat": "Product Management Dept",
    "team": "Product Team A",
    "role": "Business Analyst",
    "position": null
  },
  {
    "sr": 12,
    "id": "1013",
    "staff_id": "EMP013",
    "name": "Michael Chang",
    "email": "michael.chang@company.com",
    "doorlog": "MC013",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": false,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Quality Assurance Dept",
    "team": "Development Team B",
    "role": "Software Engineer",
    "position": null
  },
  {
    "sr": 13,
    "id": "1014",
    "staff_id": "EMP014",
    "name": "Rachel Green",
    "email": "rachel.green@company.com",
    "doorlog": "RG014",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": true,
    "div": "MKT",
    "dept_dir": "Marketing Division",
    "dept_dat": "Digital Marketing Dept",
    "team": "Marketing Team B",
    "role": "Marketing Manager",
    "position": null
  },
  {
    "sr": 14,
    "id": "1015",
    "staff_id": "EMP015",
    "name": "Daniel Kim",
    "email": "daniel.kim@company.com",
    "doorlog": "DK015",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": false,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Software Development Dept",
    "team": "Development Team A",
    "role": "Senior Developer",
    "position": null
  },
  {
    "sr": 15,
    "id": "1016",
    "staff_id": "EMP016",
    "name": "Sophia Martinez",
    "email": "sophia.martinez@company.com",
    "doorlog": "SM016",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": true,
    "div": "PROD",
    "dept_dir": "Product Division",
    "dept_dat": "Product Strategy Dept",
    "team": "Product Team B",
    "role": "Product Analyst",
    "position": null
  },
  {
    "sr": 16,
    "id": "1017",
    "staff_id": "EMP017",
    "name": "Oliver Wilson",
    "email": "oliver.wilson@company.com",
    "doorlog": "OW017",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "SALES",
    "dept_dir": "Sales Division",
    "dept_dat": "Regional Sales Dept",
    "team": "Sales Team A",
    "role": "Sales Manager",
    "position": null
  },
  {
    "sr": 17,
    "id": "1018",
    "staff_id": "EMP018",
    "name": "Emma Thompson",
    "email": "emma.thompson@company.com",
    "doorlog": "ET018",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": true,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Quality Assurance Dept",
    "team": "Development Team B",
    "role": "Tech Lead",
    "position": null
  },
  {
    "sr": 18,
    "id": "1019",
    "staff_id": "EMP019",
    "name": "William Parker",
    "email": "william.parker@company.com",
    "doorlog": "WP019",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "PROD",
    "dept_dir": "Product Division",
    "dept_dat": "Product Management Dept",
    "team": "Product Team A",
    "role": "Product Manager",
    "position": null
  },
  {
    "sr": 19,
    "id": "1020",
    "staff_id": "EMP020",
    "name": "Olivia Brown",
    "email": "olivia.brown@company.com",
    "doorlog": "OB020",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": false,
    "has_japan_business_trip": false,
    "div": "MKT",
    "dept_dir": "Marketing Division",
    "dept_dat": "Digital Marketing Dept",
    "team": "Marketing Team A",
    "role": "Social Media Manager",
    "position": null
  },
  {
    "sr": 20,
    "id": "1021",
    "staff_id": "EMP021",
    "name": "James Wilson",
    "email": "james.wilson@company.com",
    "doorlog": "JW021",
    "status": "active",
    "is_admin": false,
    "is_core_personnel": true,
    "has_japan_business_trip": true,
    "div": "ENG",
    "dept_dir": "Engineering Division",
    "dept_dat": "Infrastructure Dept",
    "team": "Development Team C",
    "role": "Software Architect",
    "position": null
  }
];

type StoreSet = (fn: (state: Employee_StoreType) => Partial<Employee_StoreType>) => void;
type StoreGet = () => Employee_StoreType;


export const employeeDataStore = (set: StoreSet, get: StoreGet) => ({
  employee_data: [],

  fetch_EmployeeData: async () => {
    set(() => ({ employee_data: employeeData }));
  },
});