INSERT IGNORE INTO role (role_name) VALUES ('Admin');
INSERT IGNORE INTO role (role_name) VALUES ('Approver');
INSERT IGNORE INTO role (role_name) VALUES ('Division_Head');
INSERT IGNORE INTO role (role_name) VALUES ('Department_Head');
INSERT IGNORE INTO role (role_name) VALUES ('Learner');

INSERT IGNORE INTO employees (
    id,
    name,
    email,
    password,
    status,
    position,
    emp_status,
    failed_login_attempts,
    role_id,
    is_core_personnel,  -- Changed from isCorePersonnel
    has_japan_business_trip,  -- Changed from hasJapanBusinessTrip
    noti_setting,  -- Changed from notiSetting
    is_deleted,  -- Changed from isDeleted
    course_announcements,
    exam_announcements,
    certificate_updates,
    email_notifications
) VALUES (
    'EMP002',
    'Admin',
    'kyawphoneygn@gmail.com',
    '$2a$10$zeb9o8Yf8aRpPnK29sjJoukzQkh.YSH2.3cTJ/6iiwPM.MfyxCtwu',
    'system', 
    '',
    'active',
    0,
    1,
    false,  -- is_core_personnel
    false,  -- has_japan_business_trip
    false,  -- noti_setting
    false,  -- is_deleted
    true,   -- course_announcements
    true,   -- exam_announcements
    true,   -- certificate_updates
    true    -- email_notifications
);

INSERT IGNORE INTO japanese_dictionary (japanese_text, english_text) VALUES 
('有','Yes'),
('なし','none'),
('管理者', 'administrator'),
('コア人材 ※FPTのみ', 'Core personnel (FPT only)'),
('デジタルソリューション研究開発部', 'Digital Solutions Research and Development Department'),
('DXシステム部', 'DX Systems Department'),
('DX推進部', 'DX Promotion Department'),
('基幹システムプラットフォーム部', 'Core Systems Platform Department'),
('資産運用プラットフォーム部', 'Asset Management Platform Department'),
('ホールセール基幹システム部', 'Wholesale Core Systems Department'),
('リテール基幹システム第一部', 'Retail Core Systems Department 1'),
('金融基幹システム部', 'Financial Systems Department'),
('ヘルステックプラットフォーム第一部', 'Health Tech Platform Division 1'),
('プラットフォーム基盤第一部', 'Platform Infrastructure Division 1'),
('プラットフォーム基盤第二部', 'Platform Infrastructure Division 2'),
('基盤システム開発第二部', 'Infrastructure Systems Development Department 2'),
('基盤技術第一部', 'Fundamental Technology Division 1'),
('リテールフロントシステム部', 'Retail Front System Department'),
('Akabot ※FPTのみ', 'Akabot (FPT only)'),
('AkaInsights ※FPTのみ', 'AkaInsights (FPT only)'),
('自動計算', 'automatic calculation'),
('アセンブラ', 'assembler'),
('非定型（修正）', 'Atypical (modified)'),
('非定型（新規）', 'Atypical (new)'),
('基本設計', 'Basic design'),
('基礎情報', 'Basic Information'),
('基礎研修', 'Basic training'),
('BIツール', 'BI tools'),
('結合試験計画', 'Bonding test plan'),
('結合試験レビュー', 'Bonding test review'),
('ミャンマー語', 'Burmese'),
('工程別', 'By process'),
('中国語', 'Chinese'),
('クラウド', 'Cloud'),
('コーディング', 'coding'),
('コーディング・単体試験計画書作成/レビュー', 'Coding and unit test plan creation/review'),
('コーディング・単体試験レビュー', 'Coding and Unit Test Review'),
('コーディングと単体テスト', 'Coding and Unit Testing'),
('コーディングレビュー', 'Coding review'),
('コーディングレビュー・単体試験計画書レビュー', 'Coding review and unit test plan review'),
('会社', 'company'),
('総合試験レビュー', 'Comprehensive Exam Review'),
('総合試験', 'Comprehensive Examination'),
('総合試験計画', 'Comprehensive Test Plan'),
('対応語学', 'Corresponding languages'),
('DATのみ', 'DAT only'),
('データベース', 'database'),
('成果物', 'deliverables'),
('詳細設計', 'detailed design'),
('詳細設計（修正）','Detailed design (revised)'),
('詳細設計（既存からの修正）', 'Detailed design (modification from existing design)'),
('詳細設計（新規作成）', 'Detailed design (new creation)'),
('詳細設計書', 'Detailed design document'),
('詳細設計レビュー', 'Detailed design review'),
('開発者（DIR業務、YSX業務限り）', 'Developer (DIR and YSX tasks only)'),
('開発', 'development'),
('開発能力', 'Development capabilities'),
('開発経験', 'Development experience'),
('開発レベル', 'Development level'),
('DIR案件', 'DIR case'),
('DIR委託元部署名', 'DIR Commissioning Department Name'),
('英語', 'English'),
('英語テストスコア', 'English test score'),
('経験', 'experience'),
('経験・対象業務経験', 'Experience / Target work experience'),
('経験レベル', 'Experience level'),
('経験年数', 'Experience years'),
('開発レベルの説明', 'Explanation of development levels'),
('外部設計', 'External design'),
('フレームワーク', 'Framework'),
('機能設計', 'Functional design'),
('部長', 'General manager'),
('グループ', 'group'),
('課長・チームリーダー', 'Head of Team'),
('最高レベル', 'highest level'),
('最高開発経験', 'Highest development experience'),
('ホスト', 'Host'),
('ホスト系', 'Host club'),
('個別開発', 'Individual development'),
('情報セキュリティ推進室', 'Information Systems Security Division'),
('インフラ', 'Infrastructure'),
('インフラ設計', 'Infrastructure design'),
('初期検証', 'Initial verification'),
('点検ツール', 'Inspection tool'),
('結合試験計画', 'Integration Test Plan'),
('日本語', 'Japanese'),
('日本語訳', 'Japanese translation'),
('日本語能力試験(JLPT)', 'JLPT'),
('リーダー', 'Leader'),
('レベル', 'level'),
('最低開発経験', 'Lowest development experience'),
('管理', 'management'),
('メインフレーム', 'Mainframe'),
('資料・ソースコードレビュー担当', 'Material/Source reviewer'),
('中間 / 中級', 'Medium / Intermediate'),
('月報', 'Monthly report'),
('名前','name'),
('国語', 'National language'),
('ネットワーク', 'Network'),
('新規作成', 'New creation'),
('非定型', 'Non-routine'),
('未経験', 'No experience'),
('オペレーティングシステム(OS)', 'Operating System (OS)'),
('業務', 'operations'),
('運用マニュアル', 'Operation manual'),
('元データ', 'Original data'),
('その他', 'others'),
('その他', 'Other'),
('概要設計', 'Outline design'),
('概要設計レビュー', 'Outline design review'),
('パッケージ', 'Package'),
('計画・設計', 'Plan / Design'),
('プログラミング', 'programming'),
('ランク', 'Rank'),
('一般社員', 'regular staff'),
('代表', 'Representative'),
('要件定義', 'Requirement definition'),
('要件定義レビュー', 'Requirements definition review'),
('役割', 'Role'),
('スコア / 得点', 'Score'),
('採点基準', 'Scoring Criteria'),
('課 / 部署', 'section'),
('課長', 'Section Manager'),
('セキュリティ', 'Security'),
('選択', 'Selection'),
('上級技術者', 'Senior engineer'),
('スキルセット', 'Skill Set'),
('システムアーキテクチャ', 'System architecture'),
('技術力', 'Technical capabilities'),
('テスト（打鍵）・定型作業コーディング・単体試験計画書作成','Testing (typing), routine tasks, coding, and unit test plan creation.'),
('合計', 'total'),
('集計', 'Totalization'),
('トレンドワード', 'Trending words'),
('単体試験', 'Unit test'),
('単体試験計画書', 'Unit test plan'),
('単体試験計画書レビュー', 'Unit test plan review'),
('ーディングレビュー・単体試験計画書レビューテスト（打鍵）・定型作業','Writing review, unit test plan review, testing (typing), routine tasks.'),
('単体試験計画書作成・単体試験計画書レビュー', 'Unit test planning and unit test review'),
('単体テスト', 'Unit testing'),
('ユーザーマニュアル', 'User Manual'),
('データベースサーバーでクエリ実行やストレージ確認を行い、CBM-NETのエラー対応およびシステム監視を担当。','I am responsible for executing queries and checking storage on the database server, as well as handling errors and system monitoring for CBM-NET.'),
('ベトナム語', 'Vietnamese'),
('BSEとして、資料やソースのレビュアー、受け入れ試験表の作成者、PGとしてSpring MVC,Spring Bootフレームワークを利用し、オンラン画面の作成、修正、UT書作成、テスト','As a BSE, I reviewed documents and source code, and created acceptance test sheets. As a PG, I used the Spring MVC and Spring Boot frameworks to create and modify online screens, write unit tests, and perform testing.'),
('週報', 'Weekly report'),
('全体', 'whole'),
('実務経験', 'Work experience'),
('その他（WindowsPhone、Tizen、Xamarin、Qt、Fluter）', 'Other (Windows Phone, Tizen, Xamarin, Qt, Fluter)'),
('先端技術', 'cutting edge technology'),
('※プルダウン入力', '*Select from the dropdown menu'),
('(会社を選択するとプルダウン表示されます','(The dropdown menu will appear once you select a company)'),
('委託元部署名', 'Name of the commissioning department'),
('技術力', 'technical ability'),
('管理経験（レベル1～5）', 'Management experience (Levels 1-5)'),
('管理能力', 'management ability'),
('語学力', 'language skills'),
('プログラミング言語', 'Programming language'),
('分散系', 'distributed system'),
('Outsystems バッチ処理', 'Outsystems batch processing'),
('経験年数', 'Years of experience'),
('経験工程', 'Experience Process'),
('年数', 'Years'),
('立場', 'position'),
('管理人数', 'Number of managers'),
('BIツール / Microsoft Power Automate/ Microsoft Power App / Tabular', 'BI tools / Microsoft Power Automate / Microsoft Power App / Tabular'),
('※DATのみ', '*DAT only'),
('Other クラウド', 'Other Cloud'),
('定型（新規）', 'Standard (new)'),
('定型（新規）2年 定型（修正）6年 ','Standard (new) 2 years Standard (revised) 6 years'),
('非定型（修正）.非定型（新規）','Atypical (revised). Atypical (new)'),
('定型（修正）', 'Standard (revised)'),
('定型', 'fixed form'),
('標準形式（新規/修正）', 'Standard format (new/modified)'),
('コーディングレビュー・ 単体試験計画書レビュー', 'Coding review and unit test plan review.'),
('コーディング・単体試験計画書作成', 'Coding and Unit Test Plan Creation'),
('詳細設計（新規）・ 詳細設計（新規）レビュー', 'Detailed design (new) / Detailed design (new) review'),
('詳細設計（修正）・ 詳細設計（修正）レビュー', 'Detailed design (revision) / Detailed design (revision) review'),
('詳細設計・コーディング・単体試験計画書レビュー','Detailed design, coding, and unit test plan review.'),
('テスト（打鍵）・定型作業', 'Testing (typing) and routine tasks'),
('テスト（打鍵）・単体試験計画書作成
テスト（打鍵）・単体試験計画書作成　レビュー
結合テスト試験仕様書・結果書作成
結合テスト試験仕様書・結果書作成 レビュー
システム更配対応
単体テストのソース調査
フロントエンド開発','Testing (keystrokes) and unit test plan creation; Testing (keystrokes) and unit test plan creation review; Integration test specification and result report creation; Integration test specification and result report creation review; System upgrade support; Unit test source code investigation; Frontend development'),
('テスト（打鍵）・単体試験計画書作成
結合テスト試験仕様書・結果書作成
システム更配対応
フロントエンド開発','Testing (keystrokes), unit test plan creation, integration test specification and results report creation, system upgrade support, front-end development.'),
('結合試験計画・結合試験レビュー', 'Bonding test planning and bonding test review'),
('結合試験計画作成','Planning of bonding tests'),
('サーバーでクエリ実行前に、プログラマーと確認を実施。','Before executing the query on the server, we performed a check with the programmer.'),
('単体試験計画書作成','Read more'),
('PGとしてSpring Batch','As a programmer, I used the Spring Batch framework to read and write files, create unit tests, and perform tests.'),
('総合試験計画・ 総合試験計画レビュー', 'Comprehensive Examination Plan / Comprehensive Examination Plan Review'),
('単体試験計画書作成', 'Unit test plan creation'),
('非定型', 'Atypical'),
('定型（修正）', 'Standard form (correction)'),
('日本出張の有無', 'Whether or not you have a business trip to Japan'),
('コア人材', 'Core personnel'),
('QCD（1～4点）', 'QCD (1-4 points)'),
('報連相（1～4点）', 'Reporting, contacting, and consulting (1-4 points)'),
('教育（1～4点）', 'Education (1-4 points)'),
('合計（レベル1～5）', 'Total (Levels 1-5)'),
('レベル（レベル1～5）', 'Level (Levels 1-5)'),
('JLPT/NAT（N1~N5）', 'JLPT/NAT (N1~N5)'),
('ホスト/オンライン', 'Host/Online'),
('ホスト/バッチ', 'Host/Batch'),
('分散/オンライン', 'Decentralized/Online'),
('分散/バッチ', 'Distributed/Batch');
